In [1]:
df.to_csv(
    r"D:\ALL PROJECTS\customer_shopping_cleaned.csv",
    index=False
)

NameError: name 'df' is not defined

In [2]:
import pandas as pd
import pyodbc
import urllib

from sqlalchemy import create_engine

# Load cleaned dataset
df = pd.read_csv(
    r"D:\ALL PROJECTS\customer_shopping_cleaned.csv"
)

# SQL Server Connection
server = "DESKTOP-10URNPC"
database = "customer_behavior"

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

print("Setup completed")

Setup completed

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\ALL PROJECTS\customer_shopping_behavior.csv')

In [3]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [14]:
df.describe() 
#gives the summary statistics of numerical columns only

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [15]:
df.describe(include='all')
##gives the summary statistics of all columns

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [4]:
df.isnull().sum()
#37 null values found in the Review Rating column

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_usd        0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [14]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [15]:
df.isnull().sum()
#All the null values in the Review Rating Column is imputed

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [19]:
#Change all column names from mixed case to lower case
df.columns = df.columns.str.lower()

#Replace all Spaces with underscores
df.columns = df.columns.str.replace(' ','_')

df = df.rename(columns={ 'purchase_amount_(usd)' : 'purchase_amount' })

In [17]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [5]:
#create a column age_group
labels= [ 'Young Adult', 'Adult', 'Middle-aged', 'Senior' ]
df[ 'age_group' ] = pd.qcut(df[ 'age' ], q=4, labels = labels)
#qcut splits the ages in to 4 equal sized groups based on data distribution and assigns the labels we've defined.

In [6]:
df[[ 'age' , 'age_group']].head(20)

    age    age_group
0    55  Middle-aged
1    19  Young Adult
2    50  Middle-aged
3    21  Young Adult
4    45  Middle-aged
5    46  Middle-aged
6    63       Senior
7    27  Young Adult
8    26  Young Adult
9    57  Middle-aged
10   53  Middle-aged
11   30  Young Adult
12   61       Senior
13   65       Senior
14   64       Senior
15   64       Senior
16   25  Young Adult
17   53  Middle-aged
18   52  Middle-aged
19   66       Senior

In [27]:
frequency_mapping = {
    'Fortnightly': 14,      
    'Weekly': 7,            
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,        
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [28]:
df[['purchase_frequency_days' , 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [29]:
df[['discount_applied' , 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [30]:
#checking for both the columns discount_applied and promo_code_used have same values. Is one of the column redundant

(df['discount_applied']== df['promo_code_used']).all()

np.True_

In [7]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group'],
      dtype='str')

In [7]:
#Both the columns discount_applied & promo_code_used gives same information. One must be removed. Removing promo_code_used
df=df.drop('promo_code_used' , axis=1)

KeyError: "['promo_code_used'] not found in axis"

In [8]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group'],
      dtype='str')

In [9]:
pip install pyodbc pandas sqlalchemy

Requirement already satisfied: pyodbc in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (5.3.0)
Requirement already satisfied: pandas in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (2.0.50)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\abhis\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pyodbc
#pyodbc is a library that allows Python to communicate with databases.
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client 11.0', 'ODBC Driver 11 for SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [10]:
from sqlalchemy import create_engine
import urllib

server = "DESKTOP-10URNPC"
database = "customer_behavior"

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

# Test connection
with engine.connect() as conn:
    print("Connection Successful!")

Connection Successful!

In [11]:
table_name = "customer"

df.to_sql(
    table_name,
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully.")

Data loaded successfully.

In [18]:
print(df.columns.tolist())

['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

In [19]:
df = df.drop('Promo Code Used', axis=1)

In [20]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='str')

In [21]:
print(df.columns.tolist())

['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

In [22]:
df.to_sql(
    "customer",
    con=engine,
    if_exists="replace",
    index=False
)

NameError: name 'engine' is not defined

In [23]:
%whos

Variable   Type         Data/Info
---------------------------------
df         DataFrame    Shape: (3900, 17)
pd         module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>

In [24]:
from sqlalchemy import create_engine
import urllib

server = "DESKTOP-10URNPC"
database = "customer_behavior"

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

print("Connection created successfully")

Connection created successfully

In [25]:
with engine.connect() as conn:
    print("Connected to SQL Server!")

Connected to SQL Server!

In [26]:
df.to_sql(
    "customer",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully.")

Data loaded successfully.

In [30]:
df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Item Purchased',
 'Category',
 'Purchase Amount (USD)',
 'Location',
 'Size',
 'Color',
 'Season',
 'Review Rating',
 'Subscription Status',
 'Shipping Type',
 'Discount Applied',
 'Previous Purchases',
 'Payment Method',
 'Frequency of Purchases']

In [31]:
df.columns = df.columns.str.replace(' ', '_')

In [32]:
print(df.columns.tolist())

['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category', 'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season', 'Review_Rating', 'Subscription_Status', 'Shipping_Type', 'Discount_Applied', 'Previous_Purchases', 'Payment_Method', 'Frequency_of_Purchases']

In [33]:
df.columns = (
    df.columns
      .str.lower()
      .str.replace(' ', '_')
)

In [34]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount_(usd)', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases']

In [35]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(' ', '_')
      .str.replace('(', '', regex=False)
      .str.replace(')', '', regex=False)
)

In [36]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount_usd', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases']

In [37]:
df.to_csv(
    r"D:\ALL PROJECTS\customer_shopping_cleaned.csv",
    index=False
)

In [38]:
df.to_sql(
    "customer",
    con=engine,
    if_exists="replace",
    index=False
)

87